//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDocMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string From { get; set; }
        public Nullable<byte> To { get; set; }
        public System.DateTime Recieved { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string Status { get; set; }
        public string Path { get; set; }
        public string Answer { get; set; }
    
        public virtual User User { get; set; }
    }
}
